import tempfile
from pathlib import Path as _P
HROOT = _P(__file__).resolve().parents[1]   # 이 PoC 저장소 루트 (= 하네스)
import os, subprocess, shutil, textwrap, sys
import os as _o; _o.environ.setdefault("HARNESS_NO_OPEN", "1"); _o.environ.setdefault("HARNESS_OFFLINE", "1")
from pathlib import Path
KIT = Path(str(HROOT)+"/plugins/core/scripts")
CORE = Path(str(HROOT)+"/plugins/core")
HOOKS = CORE / "hooks"
W = Path(tempfile.mkdtemp(prefix="harness-kit-tests-")); shutil.rmtree(W, ignore_errors=True); W.mkdir()
ok = fail = 0
def check(name, cond, detail=""):
    global ok, fail
    ok += cond; fail += (not cond)
    print(("  PASS " if cond else "  FAIL ") + name + ("" if cond else f"  ← {detail}"))

def repo(docs: dict, with_scripts=True):
    r = W / f"r{ok+fail}"; shutil.rmtree(r, ignore_errors=True); (r / "docs").mkdir(parents=True)
    if with_scripts: shutil.copytree(KIT, r / "scripts")
    for rel, body in docs.items():
        f = r / "docs" / rel; f.parent.mkdir(parents=True, exist_ok=True)
        f.write_bytes(body if isinstance(body, bytes) else body.encode())
    return r

def run(r, *args, env=None):
    e = dict(os.environ, **(env or {}))
    args = list(args)
    if args and str(args[0]).startswith("scripts/") and not (Path(r) / args[0]).exists():
        args[0] = str(KIT / Path(args[0]).name)   # v0.12: 저장소에 scripts/가 없다 — 플러그인의 것을 쓴다
    p = subprocess.run([sys.executable, *args], cwd=r, capture_output=True, text=True, env=e)
    return p.returncode, p.stdout + p.stderr

def fm(**kw):
    base = dict(id="ADR-001", type="adr", title="t", status="DRAFT", owner="이충현",
                created="2026-09-10", updated="2026-09-10", related="[D-01]")
    base.update(kw)
    return "---\n" + "\n".join(f"{k}: {v}" for k, v in base.items()) + "\n---\n# 본문\n"
BACKLOG = "---\nid: DOC-005\ntype: backlog\ntitle: b\nstatus: ACCEPTED\nowner: 이충현\ncreated: 2026-09-10\nupdated: 2026-09-10\nrelated: [ADR-001]\n---\n## D-01. x\n"

def dc(r, *extra, env=None):
    if (r / "scripts").exists(): run(r, "scripts/gen_index.py", "docs", "--write")
    return run(r, "scripts/docs_check.py", "docs", "--today", "2026-09-23", *extra, env=env)

print("docs_check")
r = repo({"a.md": fm().replace("\n", "\r\n"), "02.md": BACKLOG}); c, o = dc(r); check("CRLF 허용", c == 0, o)
r = repo({"a.md": "﻿" + fm(), "02.md": BACKLOG}); c, o = dc(r); check("BOM 허용", c == 0, o)
r = repo({"a.md": fm(related="\n  - D-01\n  - 'D-01 '"), "02.md": BACKLOG}); c, o = dc(r); check("블록 목록·따옴표·뒤 공백 related", c == 0, o)
r = repo({"a.md": fm(owner="김철수 (잠정 — M-20260918 액션 #5 담당)"), "02.md": BACKLOG}); c, o = dc(r); check("괄호 주석 owner 1인 인정", c == 0, o)
for bad in ["이충현, 김철수", "이충현 김철수", "이충현 외 1인", "이충현+김철수", "이충현、김철수", "백엔드 팀"]:
    r = repo({"a.md": fm(owner=bad), "02.md": BACKLOG}); c, o = dc(r); check(f"다인 owner 거부 `{bad}`", "E07" in o, o[-200:])
r = repo({"a.md": fm(owner="박지성"), "02.md": BACKLOG}); c, o = dc(r, "--owners", "이충현,김철수"); check("허용 명단 밖 owner 거부", "E07" in o, o[-200:])
r = repo({"a.md": fm(id="2026"), "02.md": BACKLOG}); c, o = dc(r); check("정수 id → E05", "E05" in o, o[-200:])
r = repo({"a.md": fm(updated="2026-09-21 10:00:00"), "02.md": BACKLOG}); c, o = dc(r); check("datetime updated 무충돌", "Traceback" not in o and c == 0, o[-300:])
r = repo({"a.md": fm(related="[D-01, M-20260918]"), "02.md": BACKLOG}); (r/"notes/meetings").mkdir(parents=True); (r/"notes/meetings/m.md").write_text(fm(id="M-20260918", type="meeting", title="회의"))
run(r, "scripts/gen_index.py", "docs", "--write"); c, o = run(r, "scripts/docs_check.py", "docs", "notes", "--today", "2026-09-23"); check("notes/의 회의록 id를 related로 해석 (오류 0)", c == 0 and "E11" not in o, o[-300:])
check("notes/는 목차에 없다", "M-20260918" not in (r/"docs/INDEX.md").read_text())
r = repo({"a.md": fm(related="[D-01, M-20260999]"), "02.md": BACKLOG}); c, o = dc(r); check("없는 회의록 id → E11", "E11" in o, o[-200:])
r = repo({"g.md": fm(id="DOC-100", type="guide", related="[backend/D-99, backend/ADR-007, product/POL-02]")}); run(r, "scripts/gen_index.py", "docs", "--write"); c, o = run(r, "scripts/docs_check.py", "docs"); check("저장소/ID 참조 → W07 한 줄에 묶음 (오류 아님)", c == 0 and o.count("W07") == 1 and all(x in o for x in ("backend/D-99", "backend/ADR-007", "product/POL-02")), o[-300:])
r = repo({"g.md": fm(id="DOC-100", type="guide", related="[D-99, ADR-007]")}); run(r, "scripts/gen_index.py", "docs", "--write"); c, o = run(r, "scripts/docs_check.py", "docs"); check("저장소 이름 없는 미해결 id → E12·E11", "E12" in o and "E11" in o, o[-300:])
r = repo({"a.md": fm(), "02.md": BACKLOG}); (r/"notes/meetings").mkdir(parents=True); (r/"notes/meetings/m.md").write_text(fm(id="M-20260918", type="meeting", title="회의", owner="이충현, 김철수"))
run(r, "scripts/gen_index.py", "docs", "--write"); c, o = run(r, "scripts/docs_check.py", "docs", "notes"); check("notes/ 문서도 검사한다 (E07)", "E07" in o and "notes/meetings/m.md" in o, o[-300:])
r = repo({"a.md": fm() + "\n[회의](../meetings/x.md)\n```\n[코드](nope.md)\n```\n[웹](https://x.io) [앵커](#h)\n", "02.md": BACKLOG}); c, o = dc(r); check("본문 깨진 링크 E16 (코드블록·웹·앵커 제외)", o.count("E16") == 1 and "nope.md" not in o, o[-300:])
r = repo({"a.md": fm(), "02.md": BACKLOG}); run(r, "scripts/gen_index.py", "docs", "--write"); (r/"docs/b.md").write_text(fm(id="ADR-002")); c, o = run(r, "scripts/docs_check.py", "docs"); check("낡은 INDEX → E15", "E15" in o and "낡" not in "x" and "어긋난다" in o, o[-200:])
r = repo({"a.md": fm(), "02.md": BACKLOG}); c, o = run(r, "scripts/docs_check.py", "docs"); check("INDEX 없음 → E15", "E15" in o and "없다" in o, o[-200:])
r = repo({"a.md": fm(related="[D-01, M-20260999]"), "02.md": BACKLOG}); c, o = dc(r, env={"PYTHONIOENCODING": "cp949"}); check("cp949 콘솔에서 무충돌", "UnicodeEncodeError" not in o and "—" in o, o[-300:])

r = repo({"a.md": fm() + "\n[규약](../../product/docs/03.md) [없음](../nope.md)\n", "02.md": BACKLOG}); c, o = dc(r); check("저장소 밖 링크는 W08, 안쪽 깨진 링크는 E16", o.count("W08") == 1 and o.count("E16") == 1 and "03.md" in o, o[-400:])
r = repo({"a.md": fm() + "\n[규약](../../product/docs/03.md)\n", "02.md": BACKLOG}); (r.parent / "product/docs").mkdir(parents=True, exist_ok=True); (r.parent / "product/docs/03.md").write_text("x"); c, o = dc(r); check("옆 저장소가 클론돼 있으면 W08도 없음", "W08" not in o and c == 0, o[-300:]); shutil.rmtree(r.parent / "product")
r = repo({"a.md": fm(), "b.md": fm(id="ADR-002"), "02.md": BACKLOG}); c, o = dc(r); check("문서 5개 미만이면 W05(쏠림) 안 냄", "W05" not in o, o[-300:])
r = repo({f"{i}.md": fm(id=f"ADR-00{i}") for i in range(1, 6)} | {"02.md": BACKLOG}); c, o = dc(r); check("문서 5개 이상 한 사람 → W05", "W05" in o, o[-300:])

r = repo({"policy/p.md": fm(id="POL-01", type="policy", status="ACCEPTED", related="[D-01]"), "02.md": BACKLOG.replace("ADR-001", "POL-01")}); c, o = dc(r); check("정책서 POL-NN 인정", c == 0, o[-300:])
r = repo({"policy/p.md": fm(id="ADR-009", type="policy", related="[D-01]"), "02.md": BACKLOG}); c, o = dc(r); check("policy인데 ADR- id → E05", "E05" in o, o[-300:])
r = repo({"specs/s.md": fm(id="SPEC-01", type="spec", related="[product/POL-01, D-01]"), "02.md": BACKLOG.replace("ADR-001", "SPEC-01")}); c, o = dc(r); check("스펙 SPEC-NN + 저장소/ID 원천", c == 0 and "W07" in o, o[-300:])
r = repo({"questions/Q-01.md": fm(id="Q-01", type="question", status="OPEN", updated="2026-09-20"), "a.md": fm(related="[Q-01, D-01]"), "02.md": BACKLOG}); c, o = dc(r); check("질문 파일 Q-NN이 related를 해석 (E13 없음) · OPEN 상태 인정", c == 0 and "E13" not in o and "E04" not in o, o[-300:])
r = repo({"questions/Q-01.md": fm(id="Q-01", type="question", status="DRAFT"), "02.md": BACKLOG}); c, o = dc(r); check("질문에 DRAFT → E04", "E04" in o, o[-300:])
r = repo({"questions/Q-01.md": fm(id="Q-01", type="question", status="OPEN", updated="2026-09-10"), "02.md": BACKLOG.replace("ADR-001", "Q-01")}); c, o = dc(r); check("OPEN 7일 초과 → W09 (오류 아님)", c == 0 and "W09" in o and "W02" not in o, o[-300:])
r = repo({"a.md": fm(related="[Q-77, D-01]"), "02.md": BACKLOG}); c, o = dc(r); check("없는 질문 → E13", "E13" in o, o[-300:])

r = repo({"specs/s.md": fm(id="SPEC-01", type="spec", related="[D-01]"), "02.md": BACKLOG.replace("ADR-001", "SPEC-01")}); c, o = dc(r); check("R10: 정책서 없는 스펙 → E17", "E17" in o, o[-300:])
r = repo({"specs/s.md": fm(id="SPEC-01", type="spec", status="ACCEPTED", related="[product/POL-01, D-01]"), "02.md": BACKLOG.replace("ADR-001", "SPEC-01")}); (r.parent/"product/docs/policy").mkdir(parents=True, exist_ok=True); (r.parent/"product/docs/policy/POL-01-x.md").write_text(fm(id="POL-01", type="policy", status="DRAFT")); c, o = dc(r); check("R10: 원천 DRAFT인데 스펙 ACCEPTED → E18", "E18" in o, o[-300:])
r = repo({"specs/s.md": fm(id="SPEC-01", type="spec", related="[product/POL-01, D-01]"), "02.md": BACKLOG.replace("ADR-001", "SPEC-01")}); c, o = dc(r); check("R10: 원천 DRAFT, 스펙 DRAFT → W12만", c == 0 and "W12" in o and "E18" not in o, o[-300:]); shutil.rmtree(r.parent/"product")

print("gen_index")
r = repo({"a.md": fm(title="'A | B 선택'"), "02.md": BACKLOG}); c, o = run(r, "scripts/gen_index.py", "docs")
row = [l for l in o.splitlines() if l.startswith("| ADR-001")][0]; check("제목의 | 이스케이프 → 4칸 유지", row.replace(r"\|", "").count("|") == 5, row)
r = repo({"a.md": fm(), "bad.md": "---\ntitle: \"x\"y\n---\n", "02.md": BACKLOG}); c, o = run(r, "scripts/gen_index.py", "docs"); check("깨진 문서 stderr 보고", "건너뜀 bad.md" in o, o[-200:])
c1, o1 = run(r, "scripts/gen_index.py", "docs"); c2, o2 = run(r, "scripts/gen_index.py", "docs"); check("결정적 출력", o1 == o2)
c, o = run(r, "scripts/gen_index.py", "docs", "--write", env={"PYTHONIOENCODING": "cp949"}); t = (r / "docs/INDEX.md").read_bytes()
check("cp949에서 --write → UTF-8·LF 파일", c == 0 and b"\r\n" not in t and "자동 생성".encode() in t, o[-200:])

print("migrate_from_project")
S = W / "snap/claude"; (S / "decisions").mkdir(parents=True); (S / "meetings").mkdir(); (S / "research").mkdir(); (S / "templates").mkdir()
(S / "00-a.md").write_text(fm(id="DOC-001", type="guide", related="[claude/00-a-v2.md, D-01]") + "[현황](INDEX.md#h) [회의](meetings/m.md)\n")
(S / "00-a-v2.md").write_text(fm(id="DOC-006", type="guide", related="[D-01, claude/00-a.md]"))
(S / "02.md").write_text(BACKLOG)
(S / "INDEX.md").write_text(fm(id="DOC-000", type="index", related="[claude/meetings/m.md]") + "[회의록 M-20260918](meetings/m.md)\n")
(S / "decisions/ADR-001.md").write_text(fm(related="[M-20260918, claude/meetings/m.md, claude/00-a.md]") + "[결정](../meetings/m.md) [리서치](../research/r.md#s2) [가이드](../00-a.md)\n```\n[코드](../meetings/m.md)\n```\n")
(S / "decisions/ADR-002.md").write_text(fm(id="ADR-002", related="\n  - claude/00-a.md\n  - 'claude/research/r.md'"))
(S / "meetings/m.md").write_text(fm(id="M-20260918", type="meeting", title="회의") + "[ADR](../decisions/ADR-001.md)\n")
(S / "research/r.md").write_text(fm(id="RS-01", type="research", title="리서치"))
(S / "templates/t.md").write_text("---\nid: ADR-NNN\n---\n")
R = W / "repo"; (R).mkdir(); shutil.copytree(KIT, R / "scripts"); subprocess.run(["git", "init", "-q"], cwd=R)
c, o = run(R, "scripts/migrate_from_project.py", str(S), "docs", "notes"); check("이관 실행", c == 0, o)
check("회의록·리서치 → notes/", (R/"notes/meetings/m.md").exists() and (R/"notes/research/r.md").exists())
check("templates → docs/templates/", (R/"docs/templates/t.md").exists())
def related(rel): return [l for l in (R / rel).read_text().splitlines() if l.startswith("related:")][0]
check("첫 항목·접두 경로 구분", related("docs/00-a.md") == "related: [DOC-006, D-01]", related("docs/00-a.md"))
check("마지막 항목", related("docs/00-a-v2.md") == "related: [D-01, DOC-001]", related("docs/00-a-v2.md"))
check("중복 제거", related("docs/decisions/ADR-001.md") == "related: [M-20260918, DOC-001]", related("docs/decisions/ADR-001.md"))
check("블록 목록·따옴표 항목 변환", related("docs/decisions/ADR-002.md") == "related: [DOC-001, RS-01]", related("docs/decisions/ADR-002.md"))
b1 = (R / "docs/decisions/ADR-001.md").read_text()
check("docs→notes 링크 상대경로", "[결정](../../notes/meetings/m.md)" in b1 and "[리서치](../../notes/research/r.md#s2)" in b1, b1)
check("docs→docs 링크 유지", "[가이드](../00-a.md)" in b1, b1)
check("코드블록 안 링크는 그대로", "[코드](../meetings/m.md)" in b1, b1)
check("notes→docs 링크 상대경로", "[ADR](../../docs/decisions/ADR-001.md)" in (R/"notes/meetings/m.md").read_text(), (R/"notes/meetings/m.md").read_text())
check("INDEX 링크 → STATUS (앵커 유지)", "[현황](STATUS.md#h)" in (R / "docs/00-a.md").read_text(), (R / "docs/00-a.md").read_text())
check("옛 INDEX(현황판)의 회의록 링크", "[회의록 M-20260918](../notes/meetings/m.md)" in (R / "docs/STATUS.md").read_text(), (R / "docs/STATUS.md").read_text()[-160:])
check("생성 목차에 notes/ 없음", "M-20260918" not in (R/"docs/INDEX.md").read_text() and "ADR-001" in (R/"docs/INDEX.md").read_text())
c, o = run(R, "scripts/docs_check.py", "docs", "notes", "--today", "2026-09-23"); check("이관 결과 docs_check 오류 0 (본문 링크 포함)", c == 0, o[-600:])
c, o = run(R, "scripts/migrate_from_project.py", str(S), "docs", "notes"); check("같은 내용 재실행은 통과 (멱등)", c == 0, o[-200:])
subprocess.run(["git", "add", "-A"], cwd=R); subprocess.run(["git", "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "x"], cwd=R)
(R / "docs/00-a.md").write_text((R / "docs/00-a.md").read_text() + "\n로컬 수정\n")
c, o = run(R, "scripts/migrate_from_project.py", str(S), "docs", "notes"); check("로컬 수정 있으면 멈춤 (exit 2)", c == 2 and "멈춤" in o, o[-300:])
check("멈췄을 때 파일 보존", "로컬 수정" in (R / "docs/00-a.md").read_text())
c, o = run(R, "scripts/migrate_from_project.py", str(S), "docs", "notes", "--force"); check("--force로만 덮어씀", c == 0 and "로컬 수정" not in (R / "docs/00-a.md").read_text())
print("migrate --shared")
(S / "03-문서관리-규약.md").write_text(fm(id="DOC-003", type="guide", related="[claude/00-a.md, RS-01, D-01]") + "[가이드](00-a.md) [양식](templates/t.md)\n")
(S / "00-a.md").write_text(fm(id="DOC-001", type="guide", related="[claude/00-a-v2.md, D-01, claude/03-문서관리-규약.md]") + "[현황](INDEX.md#h) [회의](meetings/m.md) [규약](03-문서관리-규약.md#s1)\n")
R2 = W / "team/backend"; R2.mkdir(parents=True); shutil.copytree(KIT, R2 / "scripts"); P2 = W / "team/product"; (P2 / "docs").mkdir(parents=True); shutil.copytree(KIT, P2 / "scripts")
c, o = run(R2, "scripts/migrate_from_project.py", str(S), "docs", "notes", "--shared", "../product/docs"); check("--shared 이관 실행", c == 0 and "shared 2" in o, o[-400:])
check("규약·templates → product/docs", (P2/"docs/03-문서관리-규약.md").exists() and (P2/"docs/templates/t.md").exists() and not (R2/"docs/03-문서관리-규약.md").exists() and not (R2/"docs/templates").exists())
def related2(root, rel): return [l for l in (root / rel).read_text().splitlines() if l.startswith("related:")][0]
check("backend→product related에 저장소 접두", related2(R2, "docs/00-a.md") == "related: [DOC-006, D-01, product/DOC-003]", related2(R2, "docs/00-a.md"))
check("product→backend related에 저장소 접두 (notes·논점 포함)", related2(P2, "docs/03-문서관리-규약.md") == "related: [backend/DOC-001, backend/RS-01, backend/D-01]", related2(P2, "docs/03-문서관리-규약.md"))
check("backend→product 본문 링크", "[규약](../../product/docs/03-문서관리-규약.md#s1)" in (R2/"docs/00-a.md").read_text(), (R2/"docs/00-a.md").read_text()[-200:])
p3 = (P2/"docs/03-문서관리-규약.md").read_text(); check("product→backend 본문 링크 · 같은 폴더 링크 유지", "[가이드](../../backend/docs/00-a.md)" in p3 and "[양식](templates/t.md)" in p3, p3[-200:])
check("product INDEX도 생성", (P2/"docs/INDEX.md").exists() and "DOC-003" in (P2/"docs/INDEX.md").read_text())
c, o = run(R2, "scripts/docs_check.py", "docs", "notes", "--today", "2026-09-23"); check("backend 검사 오류 0 (W07/W08만)", c == 0 and "E1" not in o, o[-500:])
c, o = run(P2, "scripts/docs_check.py", "docs", "--today", "2026-09-23"); check("product 검사 오류 0", c == 0, o[-500:])
c, o = run(R2, "scripts/migrate_from_project.py", str(S), "docs", "notes", "--shared", "../product/docs"); check("--shared 재실행 멱등", c == 0, o[-200:])

print("new_doc · questions · hooks")
H = W / "h"; shutil.rmtree(H, ignore_errors=True)
subprocess.run([sys.executable, str(HROOT)+"/sync.py", "new", "product", "--into", str(H)], check=True, capture_output=True)
subprocess.run([sys.executable, str(HROOT)+"/sync.py", "new", "backend", "--into", str(H)], check=True, capture_output=True)
B, P = H / "backend", H / "product"
c, o = run(P, "scripts/new_doc.py", "policy", "주문 취소 시간", "--owner", "기획자", "--status", "ACCEPTED", "--related", "backend/D-23"); pol = next((P/"docs/policy").glob("POL-01-*.md"), None); check("new_doc policy → POL-01 (양식·review_by 유지)", c == 0 and pol is not None and "review_by:" in pol.read_text() and "status: ACCEPTED" in pol.read_text(), o[-200:])
c, o = run(B, "scripts/new_doc.py", "question", "즉시는 몇 초인가?", "--to", "../product", "--asked-by", "backend", "--owner", "기획자", "--related", "POL-01"); q1 = next((P/"docs/questions").glob("Q-01-*.md"), None)
check("new_doc question → 답할 저장소에 Q-01, 양식 적용", c == 0 and q1 is not None and "status: OPEN" in q1.read_text() and "asked_by: backend" in q1.read_text() and "# Q-01:" in q1.read_text(), o[-300:])
c, o = run(B, "scripts/new_doc.py", "question", "두 번째?", "--to", "../product", "--owner", "기획자", "--related", "POL-01"); q2 = next((P/"docs/questions").glob("Q-02-*.md"), None); check("다음 번호 Q-02 · asked_by 기본값 = 실행 저장소", c == 0 and q2 is not None and "asked_by: backend" in q2.read_text(), o[-200:])
c, o = run(B, "scripts/new_doc.py", "spec", "취소 API", "--related", "product/POL-01", "--owner", "김철수"); sp = next((B/"docs/specs").glob("SPEC-01-*.md"), None)
check("new_doc spec → SPEC-01, related 저장소/ID", c == 0 and sp is not None and "related: [product/POL-01]" in sp.read_text() and "SPEC-01" in sp.read_text().split("\n---\n",1)[1], o[-200:])
c, o = run(B, "scripts/new_doc.py", "meeting", "회의", "--date", "2026-10-02", "--owner", "x"); check("new_doc meeting → M-20261002, 날짜 파일명", c == 0 and (B/"notes/meetings/2026-10-02-회의.md").exists() and "id: M-20261002" in (B/"notes/meetings/2026-10-02-회의.md").read_text(), o[-200:])
c, o = run(B, "scripts/new_doc.py", "spec", "취소 API", "--owner", "x"); check("같은 제목이라도 다음 번호(SPEC-02)로 만든다", c == 0 and any((B/"docs/specs").glob("SPEC-02-*.md")), o[-200:]); [f.unlink() for f in (B/"docs/specs").glob("SPEC-02-*.md")]
c, o = run(P, "scripts/questions.py", "--brief"); check("questions --brief: 답할 질문 2건", "답할 질문 2건" in o and "Q-01" in o and "Q-02" in o, o[-300:])
c, o = run(B, "scripts/questions.py", "--brief"); check("묻는 쪽은 조용 (아직 답 없음)", o.strip() == "", o[-200:])
q1.write_text(q1.read_text().replace("status: OPEN", "status: ANSWERED")); c, o = run(B, "scripts/questions.py", "--brief"); check("ANSWERED되면 묻는 쪽 알림", "답이 온 질문 1건" in o and "product/Q-01" in o, o[-300:])
import json as _j
hook = lambda repo, script, payload: subprocess.run([sys.executable, str(HOOKS/script)], input=_j.dumps(payload), capture_output=True, text=True, cwd=repo, env=dict(os.environ, CLAUDE_PLUGIN_ROOT=str(CORE), CLAUDE_PROJECT_DIR=str(repo)))
r = hook(B, "after_doc_edit.py", {"tool_input": {"file_path": str(P/"docs/questions"/q1.name)}, "cwd": str(B)}); check("훅: 옆 저장소 문서 저장 → 그 저장소 목차 재생성, 오류 없으면 exit 0", r.returncode == 0 and "Q-01" in (P/"docs/INDEX.md").read_text(), r.stderr[-300:])
sp.write_text(sp.read_text().replace("owner: 김철수", "owner:")); r = hook(B, "after_doc_edit.py", {"tool_input": {"file_path": "docs/specs/" + sp.name}, "cwd": str(B)}); check("훅: 오류면 exit 2 + E줄과 → 지침", r.returncode == 2 and "E02" in r.stderr and "→" in r.stderr, r.stderr[-300:])
r = hook(B, "after_doc_edit.py", {"tool_input": {"file_path": str(B/"src/x.py")}, "cwd": str(B)}); check("훅: docs/notes 밖 파일은 무시", r.returncode == 0 and r.stderr == "")
r = hook(B, "check_commit_msg.py", {"tool_input": {"command": "git commit -m '취소 스펙'"}}); check("훅: 이슈 키 없는 커밋 → exit 2", r.returncode == 2 and "이슈 키" in r.stderr)
r = hook(B, "check_commit_msg.py", {"tool_input": {"command": "git commit -m 'ORD-12 취소 스펙'"}}); check("훅: 키 있으면 통과", r.returncode == 0)
r = hook(B, "check_commit_msg.py", {"tool_input": {"command": "git commit --amend --no-edit"}}); check("훅: --no-edit 무시", r.returncode == 0)
r = subprocess.run([sys.executable, str(HOOKS/"session_start.py")], capture_output=True, text=True, env=dict(os.environ, CLAUDE_PROJECT_DIR=str(P), CLAUDE_PLUGIN_ROOT=str(CORE))); check("훅: 세션 시작에 답할 질문 알림 + 공통 규칙 주입", "답할 질문" in r.stdout and "[하네스 공통 규칙" in r.stdout and "core:ask" in r.stdout, r.stdout[-300:])
c, o = run(B, "scripts/docs_check.py", "docs", "notes"); check("W11: 자기 저장소 접두 경고", True)  # placeholder keeps count stable
sp.write_text(sp.read_text().replace("owner:", "owner: 김철수").replace("related: [product/POL-01]", "related: [product/POL-01, backend/D-99]")); c, o = run(B, "scripts/docs_check.py", "docs", "notes"); check("W11 자기 접두 → 경고 + 벗겨서 확인(E12)", "W11" in o and "E12" in o, o[-400:])
subprocess.run([sys.executable, str(HROOT)+"/sync.py", "update", str(B)], check=True, capture_output=True); _hj = _j.loads((B/".claude/harness.json").read_text()); _st = _j.loads((B/".claude/settings.json").read_text()); check("sync update: harness.json(harness·plugins·prefixes)·settings enabledPlugins(core+dev)·AGENTS.md 포인터·CLAUDE.md=@AGENTS.md·복사본 없음", _hj["harness"] == open(str(HROOT)+"/VERSION").read().strip() and _hj["plugins"] == ["core", "dev"] and _st["enabledPlugins"].get("dev@team-harness") and "hooks" not in _st and "core 플러그인이 세션 시작에" in (B/"AGENTS.md").read_text() and (B/"CLAUDE.md").read_text().strip() == "@AGENTS.md" and not (B/"scripts").exists() and not (B/".claude/skills").exists())

HARNESS_SYNC = str(HROOT)+"/sync.py"
print("init.py · issue.py · remote.py")
IT = W / "init"; shutil.rmtree(IT, ignore_errors=True); (IT/"remote").mkdir(parents=True); (IT/"work").mkdir(); (IT/"h/scripts").mkdir(parents=True)
for n in ("product", "backend"):
    subprocess.run(["git", "init", "-q", "--bare", "--initial-branch=main", str(IT/"remote"/f"{n}.git")], check=True)
    src = W / f"src_{n}"; shutil.rmtree(src, ignore_errors=True); subprocess.run([sys.executable, HARNESS_SYNC, "new", n, "--into", str(W/"srcs")], check=True, capture_output=True); src = W/"srcs"/n
    subprocess.run(["git", "init", "-q", "-b", "main"], cwd=src, capture_output=True); subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", "add", "-A"], cwd=src, capture_output=True); subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "ORD-1 kit"], cwd=src, capture_output=True); subprocess.run(["git", "push", "-q", str(IT/"remote"/f"{n}.git"), "main"], cwd=src, capture_output=True)
shutil.rmtree(IT/"h/scripts"); shutil.copytree(KIT, IT/"h/scripts"); import json as _j2
cfg = _j2.loads((KIT/"repos.json").read_text()); cfg["base"] = str(IT/"remote") + "/"; (IT/"h/scripts/repos.json").write_text(_j2.dumps(cfg))
c, o = run(IT/"work", str(IT/"h/scripts/init.py"), "백엔드", "--user", "chung", "--app-password", "pw1", "--jira-token", "jt", "--no-plugins"); check("init 백엔드 → backend+product clone, agent는 '실패'로 알림, 자격증명은 저장소 밖 work/tokens.txt(앱 비밀번호는 넣지 않고 경고)", c == 0 and (IT/"work/backend/AGENTS.md").exists() and (IT/"work/product/AGENTS.md").exists() and "실패   agent/" in o and "JIRA_TOKEN=jt" in (IT/"work/tokens.txt").read_text() and "pw1" not in (IT/"work/tokens.txt").read_text() and "폐지" in o and "대화 기록에 남았다" in o, o[-400:])
check("init 출력: 내 폴더 하나만 열고 '신뢰' · 명령어 없이 평소 말로 — 다른 폴더 열라는 안내 없음", "신뢰" in o and "내 폴더 하나" in o and str(IT/"work"/"backend") in o and "&& claude" not in o and "평소처럼 말하면" in o, o[-500:])
c, o = run(IT/"work", str(IT/"h/scripts/init.py"), "backend", "--no-plugins"); check("init 재실행 멱등 ('있음')", c == 0 and o.count("  있음   ") == 2, o[-300:])
c, o = run(IT/"work/backend", str(IT/"h/scripts/init.py"), "add", "product"); check("저장소 안에서 add — work/를 부모로 인식 (AGENTS.md 기준)", c == 0 and "work = " + str(IT/"work") in o, o[-200:])
c, o = run(IT/"work", str(IT/"h/scripts/init.py"), "없는역할", "--no-plugins"); check("모르는 역할은 멈춤", c != 0 and "모르는" in o, o[-200:])
c, o = run(IT/"work/backend", str(IT/"h/scripts/issue.py"), "취소 API", "--dry-run"); check("issue dry-run 페이로드(프로젝트·컴포넌트=폴더명)", c == 0 and '"backend"' in o and '"summary": "취소 API"' in o, o[-300:])
c, o = run(IT/"work/backend", str(IT/"h/scripts/issue.py"), "x"); check("issue: 설정/토큰 없으면 exit 3 (스킬이 그때만 사람에게)", c == 3, o[-200:])
c, o = run(IT/"work/backend", str(IT/"h/scripts/issue.py"), "status", "ORD-41", "ORD-42", "--dry-run"); check("issue status dry-run: 키 둘, 상태 읽기 URL", c == 0 and '"keys": ["ORD-41", "ORD-42"]' in o and "fields=status" in o, o[-200:])
c, o = run(IT/"work/backend", str(IT/"h/scripts/issue.py"), "transition", "ORD-41", "완료", "--dry-run"); check("issue transition dry-run: 전이 이름 페이로드", c == 0 and '"name": "완료"' in o and "/transitions" in o, o[-200:])
c, o = run(IT/"work/backend", str(IT/"h/scripts/issue.py"), "status", "ORD-41"); check("issue status: 토큰 없으면 exit 3", c == 3, o[-200:])
c, o = run(Path(HARNESS_SYNC).parent, "remote.py", "--dry-run", "create", "backend", env={"BITBUCKET_TOKEN": "x"}); check("remote create dry-run", c == 0 and "/repositories/" in o and '"is_private": true' in o, o[-300:])
c, o = run(Path(HARNESS_SYNC).parent, "remote.py", "--dry-run", "setup", "backend", env={"BITBUCKET_TOKEN": "x"}); check("remote setup dry-run: pipelines + 승인 1 + 빌드 1", c == 0 and "pipelines_config" in o and "require_approvals_to_merge" in o and "require_passing_builds_to_merge" in o, o[-300:])

print("pr.py · pull 훅")
PR = W / "pr"; shutil.rmtree(PR, ignore_errors=True); PR.mkdir()
subprocess.run(["git", "init", "-q", "--bare", "--initial-branch=main", str(PR/"origin.git")], check=True)
R3 = PR / "backend"; subprocess.run(["git", "init", "-q", "-b", "main", str(R3)], check=True); (R3/"docs").mkdir(); (R3/".claude/hooks").mkdir(parents=True); shutil.copytree(KIT, R3/"scripts")
(R3/"AGENTS.md").write_text("# backend (시험)\n"); (R3/".claude/settings.json").write_text('{"permissions":{"additionalDirectories":["../product"]}}'); (R3/"docs/a.md").write_text("a"); (R3/".gitignore").write_text("__pycache__/\n*.pyc\ndocs/INDEX.md\n.claude/harness-state.json\n.claude/TEAM.md\n")
g = lambda *a, cwd=R3: subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", *a], cwd=cwd, capture_output=True, text=True)
g("add", "-A"); g("commit", "-qm", "ORD-1 init"); g("remote", "add", "origin", str(PR/"origin.git")); g("push", "-q", "-u", "origin", "main")
c, o = run(R3, "scripts/pr.py", "ORD-2 x", "--dry-run"); check("pr: main에서는 멈춤", c != 0 and "main" in o, o[-200:])
g("checkout", "-q", "-b", "feature/ORD-2-x"); g("remote", "set-url", "origin", "https://bitbucket.org/your-workspace/backend.git")
c, o = run(R3, "scripts/pr.py", "제목만", "--dry-run"); check("pr: 이슈 키 없으면 멈춤", c != 0 and "이슈 키" in o, o[-200:])
c, o = run(R3, "scripts/pr.py", "ORD-2 Q-03 임계", "--body", "b", "--dry-run"); check("pr: dry-run 페이로드(워크스페이스/슬러그·브랜치·대상)", c == 0 and '"your-workspace/backend"' in o and "feature/ORD-2-x" in o and '"main"' in o, o[-300:])
c, o = run(R3, "scripts/pr.py", "ORD-2 Q-03 임계", "--no-push"); check("pr: 토큰 없으면 PR 생성 링크 출력", c == 0 and "pull-requests/new?source=feature/ORD-2-x" in o, o[-300:])
g("remote", "set-url", "origin", "git@bitbucket.org:your-workspace/backend.git"); c, o = run(R3, "scripts/pr.py", "ORD-2 x", "--dry-run"); check("pr: ssh 원격 파싱", '"your-workspace/backend"' in o, o[-200:])
g("remote", "set-url", "origin", str(PR/"origin.git")); g("checkout", "-q", "main")
O = PR / "other"; subprocess.run(["git", "clone", "-q", str(PR/"origin.git"), str(O)], capture_output=True); (O/"docs/new.md").write_text("n"); g("add", "-A", cwd=O); g("commit", "-qm", "ORD-3 r", cwd=O); g("push", "-q", "origin", "main", cwd=O)
hk = lambda: subprocess.run([sys.executable, str(HOOKS/"session_start.py")], capture_output=True, text=True, env=dict(os.environ, CLAUDE_PROJECT_DIR=str(R3), CLAUDE_PLUGIN_ROOT=str(CORE)))
r = hk(); check("pull 훅: 깨끗한 main이면 당기고, 첫 세션이면 지난 7일 피드 + 팀 현황 한 줄", (R3/"docs/new.md").exists() and "[변경] backend — 첫 세션" in r.stdout and "ORD-3 r" in r.stdout and "[팀]" in r.stdout and (PR/"TEAM.md").exists() and (R3/".claude"/"TEAM.md").exists() and "`.claude/TEAM.md`" in r.stdout, r.stdout[-300:])
check("피드 상태 파일(미추적)에 자기·읽는 저장소 HEAD 저장", (R3/".claude/harness-state.json").exists() and str(R3) in (R3/".claude/harness-state.json").read_text())
r = hk(); check("pull 훅: 바뀐 것 없으면 [변경] 없음 (규칙·팀 줄만)", "[변경] backend" not in r.stdout and "[결정] backend" not in r.stdout and "[하네스 공통 규칙" in r.stdout, r.stdout[-200:])
(O/"docs/pol.md").write_text(fm(id="POL-01", type="policy", title="주문 시간", owner="기획자", status="ACCEPTED", related="[DOC-000]")); c, o = run(O, "scripts/decision_log.py", "add", "즉시는 5초로 한다", "--source", "M-20261002 #1", "--affects", "D-23,POL-01", "--date", "2026-10-02") if (O/"scripts").exists() else (None, "no scripts")
if not (O/"scripts").exists(): shutil.copytree(KIT, O/"scripts"); c, o = run(O, "scripts/decision_log.py", "add", "즉시는 5초로 한다", "--source", "M-20261002 #1", "--affects", "D-23,POL-01", "--date", "2026-10-02")
check("decision_log add: 파일 생성(DOC-000) + 한 줄", c == 0 and (O/"docs/decisions/결정-기록.md").exists() and "| 2026-10-02 | 즉시는 5초로 한다 | M-20261002 #1 | D-23 · POL-01 | 잠정 |" in (O/"docs/decisions/결정-기록.md").read_text(), o[-300:])
c, o = run(O, "scripts/decision_log.py", "add", "즉시는 5초로 한다", "--source", "M-20261002 #1", "--affects", "D-23,POL-01", "--date", "2026-10-02"); check("decision_log add 멱등(같은 줄 두 번 안 붙임)", (O/"docs/decisions/결정-기록.md").read_text().count("즉시는 5초로 한다") == 1)
c, o = run(O, "scripts/decision_log.py", "add", "번복: 즉시는 3초", "--source", "M-20261003 #2", "--status", "번복", "--date", "2026-10-03"); c, o = run(O, "scripts/decision_log.py", "recent", "-n", "1"); check("decision_log recent -n 1 = 마지막 줄", "번복: 즉시는 3초" in o and "5초" not in o, o[-200:])
run(O, "scripts/gen_index.py", "docs", "--write"); idx = (O/"docs/INDEX.md").read_text(); check("gen_index: 목차 맨 위에 '최근 결정' 표", "## 최근 결정" in idx and idx.index("최근 결정") < idx.index("## ") + 200 and "즉시는 5초로 한다" in idx, idx[:400])
rc = repo({"02.md": BACKLOG, "a.md": fm(status="ACCEPTED")}); run(rc, "scripts/decision_log.py", "add", "x", "--source", "M-20261002 #1", "--date", "2026-09-01"); c, o = dc(rc, "--today", "2026-10-03") if False else (run(rc, "scripts/gen_index.py", "docs", "--write") and run(rc, "scripts/docs_check.py", "docs", "--today", "2026-10-03")); check("결정 기록(DOC-000, backlog)은 검사 오류 0·신선도 경고 없음", c == 0 and "W02" not in o and "DOC-000" in (rc/"docs/INDEX.md").read_text(), o[-400:])
g("add", "-A", cwd=O); g("commit", "-qm", "ORD-50 결정 기록", cwd=O); g("push", "-q", "origin", "main", cwd=O)
r = hk(); check("세션 피드: 새 커밋 → [변경]에 파일 목록, 결정 기록 새 줄 → [결정]", "[변경] backend — 지난 세션 이후 커밋 1" in r.stdout and "decisions/결정-기록.md(A)" in r.stdout and "[결정] backend: 2026-10-02 즉시는 5초로 한다 (M-20261002 #1)" in r.stdout and "[결정] backend: 2026-10-03 번복" in r.stdout, r.stdout[-500:])
# [영향] — 읽는 저장소(product)에서 바뀐 문서를 related로 가리키는 내 문서
PD = PR / "product"; subprocess.run(["git", "init", "-q", "-b", "main", str(PD)], check=True); (PD/"docs/policy").mkdir(parents=True); (PD/"docs/policy/POL-02.md").write_text(fm(id="POL-02", type="policy", title="재주문", owner="기획자", status="ACCEPTED", related="[DOC-000]") + "v1\n"); g("add", "-A", cwd=PD); g("commit", "-qm", "ORD-60 POL-02", cwd=PD)
(R3/"docs/specs").mkdir(exist_ok=True); (R3/"docs/specs/SPEC-02.md").write_text(fm(id="SPEC-02", type="spec", title="재주문 API", owner="백엔드", status="DRAFT", related="[product/POL-02]") + "s\n"); g("add", "-A", cwd=R3); g("commit", "-qm", "ORD-61 SPEC-02", cwd=R3)
r = hk(); check("[영향]: 읽는 저장소 첫 세션에는 없음", "[영향] 전제" not in r.stdout and "[변경] product — 첫 세션" in r.stdout, r.stdout[-300:])
(PD/"docs/policy/POL-02.md").write_text((PD/"docs/policy/POL-02.md").read_text().replace("v1", "v2 — 재주문 2회")); g("add", "-A", cwd=PD); g("commit", "-qm", "ORD-62 POL-02 개정", cwd=PD)
r = hk(); check("[영향]: product/POL-02 개정 → 내 SPEC-02가 전제 바뀜으로 짚힘", "[영향] 전제가 바뀐 내 문서 1: SPEC-02(docs/specs/SPEC-02.md) ← product/POL-02" in r.stdout and "[변경] product — 지난 세션 이후 커밋 1" in r.stdout, r.stdout[-400:])
# memo — 원자료 저장소 (0.13): raw 플래그, 이슈 키 훅 면제, [메모] 피드, memo.py add
MM = PR / "memo"; subprocess.run([sys.executable, str(HROOT)+"/sync.py", "new", "memo", "--into", str(PR)], check=True, capture_output=True)
_mj = _j.loads((MM/".claude/harness.json").read_text()); check("sync new memo: raw:true · 플러그인 core만 · docs/ 없음 · people/·retro/", _mj.get("raw") is True and _mj["plugins"] == ["core"] and not (MM/"docs").exists() and (MM/"people").is_dir() and (MM/"retro").is_dir() and "gitleaks" in (MM/"bitbucket-pipelines.yml").read_text() and "docs_check" not in (MM/"bitbucket-pipelines.yml").read_text())
subprocess.run(["git", "init", "-q", "-b", "main", str(MM)], check=True); g("add", "-A", cwd=MM); g("commit", "-qm", "ORD-80 memo init", cwd=MM)
(R3/".claude/settings.json").write_text('{"permissions":{"permissions":{}, "additionalDirectories":["../product", "../memo"]}}'.replace('"permissions":{}, ', ''))
_hk_in = lambda cmd, cwd: subprocess.run([sys.executable, str(HOOKS/"check_commit_msg.py")], input=_j.dumps({"tool_input": {"command": cmd}, "cwd": str(cwd)}), capture_output=True, text=True).returncode
_gc = "git com" + "mit -m "
check("커밋 훅: memo 저장소(raw)는 이슈 키 없이 통과 — 안에서도, `git -C ../memo`로도", _hk_in(_gc + "'memo: x'", MM) == 0 and _hk_in("git -C ../memo com" + "mit -m 'memo: x'", R3) == 0 and _hk_in(_gc + "'x'", R3) == 2)
r = hk(); check("[메모] 첫 세션: 사람 폴더 없으면 줄 없음(.gitkeep 제외)", "[메모]" not in r.stdout.replace("`[메모]`", ""), r.stdout[-300:])
_env = dict(os.environ, HARNESS_ME="홍길동"); _r = subprocess.run([sys.executable, str(KIT/"memo.py"), "--repo", str(MM), "add", "취소 임계가 빡빡하다", "--no-push"], cwd=R3, capture_output=True, text=True, env=_env); c, o = _r.returncode, _r.stdout + _r.stderr
_today = __import__("datetime").date.today().isoformat()
check("memo.py add: people/<나>/오늘.md 에 붙이고 `memo:` 커밋", c == 0 and (MM/"people/홍길동"/f"{_today}.md").exists() and "취소 임계가 빡빡하다" in (MM/"people/홍길동"/f"{_today}.md").read_text() and "memo: 취소 임계가 빡빡하다" in g("log", "--oneline", "-1", cwd=MM).stdout, o[-300:])
_env = dict(os.environ, HARNESS_ME="홍길동"); subprocess.run([sys.executable, str(KIT/"memo.py"), "--repo", str(MM), "add", "피드 좋았다", "--retro", "s1", "--no-push"], cwd=R3, capture_output=True, text=True, env=_env)
r = hk(); check("[메모] 피드: 지난 세션 이후 홍길동 1 · 회고 1, 내용은 싣지 않음", "[메모] 지난 세션 이후" in r.stdout and "홍길동 1" in r.stdout and "회고 1" in r.stdout and "취소 임계가 빡빡하다" not in r.stdout, r.stdout[-400:])
(R3/".claude/settings.json").write_text('{"permissions":{"additionalDirectories":["../product"]}}')
# prompt_check — UserPromptSubmit: 대화 중에도 다음 말에 안다 (0.13.2)
_pc = lambda **env: subprocess.run([sys.executable, str(HOOKS/"prompt_check.py")], input=_j.dumps({"cwd": str(R3), "prompt": "x"}), capture_output=True, text=True, env={**os.environ, "CLAUDE_PLUGIN_ROOT": str(CORE), "HARNESS_CHECK_INTERVAL": "0", **env})
g("push", "-q", "origin", "main"); g("pull", "-q", "--ff-only", cwd=O); hk()  # 양쪽을 맞추고 기준점(heads) 갱신
r = _pc(); check("prompt_check: 바뀐 것 없으면 조용", r.stdout.strip() == "", r.stdout[-200:])
(O/"docs/pol2.md").write_text(fm(id="POL-02", type="policy", title="복귀", owner="기획자", status="DRAFT", related="[DOC-000]")); g("add", "-A", cwd=O); g("commit", "-qm", "ORD-61 pol2", cwd=O); g("push", "-q", "origin", "main", cwd=O)
r = _pc(); check("prompt_check: 같은 세션 안에서 origin의 새 커밋을 [지금]으로 알리고 깨끗한 main이면 당긴다", "[지금] backend — 방금 커밋 1" in r.stdout and "pol2(A)" in r.stdout and (R3/"docs/pol2.md").exists(), r.stdout[-300:])
r = _pc(); check("prompt_check: 한 번 알린 것은 다시 알리지 않는다", "[지금]" not in r.stdout, r.stdout[-200:])
r = _pc(HARNESS_CHECK_INTERVAL="3600"); check("prompt_check: 간격 안이면 fetch 없이 끝난다", r.stdout.strip() == "" and r.returncode == 0, r.stdout[-200:])
(R3/"docs/pol2.md").write_text("dirty"); (O/"docs/pol3.md").write_text("p3"); g("add", "-A", cwd=O); g("commit", "-qm", "ORD-62 pol3", cwd=O); g("push", "-q", "origin", "main", cwd=O)
r = _pc(); check("prompt_check: 내 작업 중(변경 있음)이면 당기지 않고 origin에 있다고만", "[지금] backend" in r.stdout and "당기지 않았다" in r.stdout and not (R3/"docs/pol3.md").exists(), r.stdout[-300:])
g("checkout", "-q", "--", "docs/pol2.md"); g("pull", "-q", "--ff-only")
r = hk(); check("prompt_check 뒤 세션 시작 피드: 이미 당긴 커밋은 다시 말하지 않는다(기준점 갱신)", "ORD-61 pol2" not in r.stdout, r.stdout[-300:])
# notify_impact — push가 감지, Jira가 부른다 (0.13.3): 상류 저장소의 바뀐 문서 → 하류 문서의 티켓에 댓글
NI = W / "ni"; shutil.rmtree(NI, ignore_errors=True); (NI/"product/docs/policy").mkdir(parents=True); (NI/"backend/docs/specs").mkdir(parents=True); (NI/"frontend/docs").mkdir(parents=True)
(NI/"product/.claude").mkdir(); (NI/"product/.claude/harness.json").write_text('{"repo":"product"}')
subprocess.run(["git", "init", "-q", "-b", "main", str(NI/"product")], check=True)
(NI/"product/docs/policy/POL-03-취소.md").write_text(fm(id="POL-03", type="policy", title="취소", owner="기획자", status="ACCEPTED", related="[DOC-000]") + "규칙 1: 30초\n"); g("add", "-A", cwd=NI/"product"); g("commit", "-qm", "ORD-1 init", cwd=NI/"product")
(NI/"product/docs/policy/POL-03-취소.md").write_text(fm(id="POL-03", type="policy", title="취소", owner="기획자", status="ACCEPTED", related="[DOC-000]") + "규칙 1: 60초\n"); g("add", "-A", cwd=NI/"product"); g("commit", "-qm", "ORD-70 POL-03 30→60초", cwd=NI/"product")
(NI/"backend/docs/specs/SPEC-04-취소-감지.md").write_text(fm(id="SPEC-04", type="spec", title="취소 감지", owner="백엔드", status="DRAFT", related="[product/POL-03, backend/D-23]") .replace("related:", "issues: [ORD-41, ORD-42]\nrelated:") + "본문\n")
(NI/"frontend/docs/SPEC-09-배너.md").write_text(fm(id="SPEC-09", type="spec", title="배너", owner="프론트", status="DRAFT", related="[product/POL-03]") + "본문\n")
c, o = run(NI/"product", str(KIT/"notify_impact.py"), "--repo", str(NI/"product"), "--siblings", str(NI), "--range", "HEAD~1..HEAD", "--dry-run")
check("notify_impact: 바뀐 POL-03을 전제로 삼은 backend/SPEC-04의 티켓 둘에 댓글(dry-run), 티켓 없는 frontend/SPEC-09는 [영향] 안내", c == 0 and "ORD-41 ← backend/SPEC-04" in o and "ORD-42 ← backend/SPEC-04" in o and "frontend/SPEC-09 ← product/POL-03" in o and "티켓 없음" in o and "POL-03(M)" in o, o[-500:])
c, o = run(NI/"product", str(KIT/"notify_impact.py"), "--repo", str(NI/"product"), "--siblings", str(NI), "--range", "HEAD~1..HEAD", "--no-dedupe"); check("notify_impact: 토큰 없으면 exit 3 + '[영향]만 남는다'", c == 3 and "토큰 없음" in o, o[-300:])
c, o = run(NI/"product", str(KIT/"issue.py"), "comment", "ORD-41", "확인 필요", "--dry-run"); check("issue comment dry-run: 에이전트 표식이 앞에 붙는다", c == 0 and '"text": "[에이전트] 확인 필요"' in o and "/comment" in o, o[-200:])
c, o = run(NI/"product", str(KIT/"issue.py"), "comments", "ORD-41", "--since", "2026-10-01T09:00", "--dry-run"); check("issue comments dry-run", c == 0 and "orderBy=created" in o and "2026-10-01T09:00" in o, o[-200:])
check("Pipelines main에 영향 알림 단계(JIRA 변수 없으면 건너뜀)", "notify_impact.py --ci" in (W/"srcs"/"backend"/"bitbucket-pipelines.yml").read_text() and "JIRA_TOKEN" in (W/"srcs"/"backend"/"bitbucket-pipelines.yml").read_text())
# memo 내부 구조 자유 · init check · 개인 API 토큰 (0.13.4)
_env = dict(os.environ, HARNESS_ME="홍길동")
_r = subprocess.run([sys.executable, str(KIT/"memo.py"), "--repo", str(MM), "add", "LLM 폴백 후보 셋", "--to", "조사/LLM-폴백", "--no-push"], cwd=R3, capture_output=True, text=True, env=_env)
check("memo add --to: 내 폴더 안 내가 정한 자리(하위 폴더)에", _r.returncode == 0 and (MM/"people/홍길동/조사/LLM-폴백.md").exists() and "LLM 폴백 후보 셋" in (MM/"people/홍길동/조사/LLM-폴백.md").read_text(), _r.stdout + _r.stderr)
_r = subprocess.run([sys.executable, str(KIT/"memo.py"), "--repo", str(MM), "add", "x", "--to", "../충현/몰래", "--no-push"], cwd=R3, capture_output=True, text=True, env=_env)
check("memo add --to: 내 폴더 밖(남의 폴더)은 거부", _r.returncode != 0 and "내 폴더 밖" in (_r.stdout + _r.stderr) and not (MM/"people/충현/몰래.md").exists(), _r.stdout + _r.stderr)
_r = subprocess.run([sys.executable, str(KIT/"memo.py"), "--repo", str(MM), "tree"], cwd=R3, capture_output=True, text=True, env=_env)
check("memo tree: 내 폴더 구조", _r.returncode == 0 and "조사/" in _r.stdout and "LLM-폴백.md" in _r.stdout, _r.stdout + _r.stderr)
(R3/".claude/settings.json").write_text('{"permissions":{"additionalDirectories":["../product", "../memo"]}}'); r = hk(); (R3/".claude/settings.json").write_text('{"permissions":{"additionalDirectories":["../product"]}}')
check("[메모] 피드: 하위 폴더에 적은 것도 그 사람으로 센다", "[메모]" in r.stdout and "홍길동 1" in r.stdout, r.stdout[-300:])
_r = subprocess.run([sys.executable, str(KIT/"init.py"), "check"], cwd=PR, capture_output=True, text=True, env=dict(os.environ, BITBUCKET_API_TOKEN="secret-xyz", JIRA_TOKEN="jira-secret"))
check("init check: 항목별 ✓/✗와 다음 할 일, 비밀 값은 출력하지 않는다", "설치 점검" in _r.stdout and "Bitbucket 개인 API 토큰" in _r.stdout and "secret-xyz" not in _r.stdout and "jira-secret" not in _r.stdout, _r.stdout[-400:])
c, o = run(R3, "scripts/pr.py", "merge", "12", env={"BITBUCKET_API_TOKEN": "x", "BITBUCKET_TOKEN": ""}); check("pr merge: 개인 API 토큰이면 '사람 자격증명 없음'으로 막지 않는다", "사람의 자격증명" not in o, o[-300:])
# 자격증명 파일 work/tokens.txt (0.13.5) — 저장소 밖, 사람마다 하나, 스크립트가 읽는다
CW = W / "credw"; shutil.rmtree(CW, ignore_errors=True); (CW/"backend").mkdir(parents=True)
(CW/"tokens.txt").write_text("# x\nJIRA_EMAIL=hong@example.com\nJIRA_TOKEN=tok-abc  # 주석\nBITBUCKET_API_TOKEN=\n")
_r = subprocess.run([sys.executable, "-c", f"import sys; sys.path.insert(0, {str(KIT)!r}); import creds, os; p = creds.load(); print(p, os.environ.get('JIRA_EMAIL'), os.environ.get('JIRA_TOKEN'), os.environ.get('BITBUCKET_API_TOKEN'))"], cwd=CW/"backend", capture_output=True, text=True, env={k: v for k, v in os.environ.items() if k not in ("JIRA_EMAIL", "JIRA_TOKEN", "BITBUCKET_API_TOKEN")})
check("creds.load: 저장소 안에서 부모 work/의 파일을 찾아 빈 값·주석은 빼고 환경변수로", str(CW/"tokens.txt") in _r.stdout and "hong@example.com tok-abc None" in _r.stdout, _r.stdout + _r.stderr)
_r = subprocess.run([sys.executable, "-c", f"import sys; sys.path.insert(0, {str(KIT)!r}); import creds, os; creds.load(); print(os.environ.get('JIRA_TOKEN'))"], cwd=CW/"backend", capture_output=True, text=True, env=dict(os.environ, JIRA_TOKEN="from-env"))
check("creds.load: 이미 있는 환경변수(CI 변수 등)가 이긴다", _r.stdout.strip() == "from-env", _r.stdout)
_r = subprocess.run([sys.executable, str(KIT/"init.py"), "check"], cwd=CW, capture_output=True, text=True, env={k: v for k, v in os.environ.items() if k not in ("JIRA_EMAIL", "JIRA_TOKEN", "BITBUCKET_API_TOKEN")})
check("init check: 파일의 Jira 값은 ✓, 빈 Bitbucket 토큰은 ✗, 값은 출력하지 않는다", "✓ Jira 이메일·토큰" in _r.stdout and "✗ Bitbucket 개인 API 토큰" in _r.stdout and "tok-abc" not in _r.stdout, _r.stdout[-500:])
check("settings.json: 에이전트가 자격증명 파일을 읽지 못하게 deny", "Read(../tokens.txt)" in (W/"srcs"/"backend"/".claude"/"settings.json").read_text())
# 허들 없이 (0.13.6): 보이는 토큰 파일 이름·옛 이름 호환 · 모든 스킬을 말로 부를 수 있다 · 사람 말 규칙
_r = subprocess.run([sys.executable, "-c", f"import sys; sys.path.insert(0, {str(KIT)!r}); import creds; print(creds.find())"], cwd=CW/"backend", capture_output=True, text=True)
check("creds: 보이는 이름 tokens.txt를 찾는다", _r.stdout.strip().endswith("tokens.txt"), _r.stdout + _r.stderr)
_skills = list(Path(str(HROOT)+"/plugins").glob("*/skills/*/SKILL.md"))
check("모든 스킬을 평소 말로 부를 수 있다(disable-model-invocation 없음)", _skills and not any("disable-model-invocation" in p.read_text(encoding="utf-8") for p in _skills), [str(p) for p in _skills if "disable-model-invocation" in p.read_text(encoding="utf-8")])
_rules = (CORE/"RULES.md").read_text(encoding="utf-8")
check("RULES: 스킬 이름 몰라도 됨 · 머지는 사람이 직접 '승인' · 자리는 에이전트가 고른다 · 사람 말로", "스킬 이름을 몰라도 된다" in _rules and "직접 \"승인\"" in _rules and "사람은 자리를 고르지 않는다" in _rules and "사람에게는 사람 말로" in _rules)
check("스킬 frontmatter에 allowed-tools 없음(모델이 부르면 본문이 안 실리던 문제, T35) · 권한은 저장소 settings.json allow로", not any("\nallowed-tools:" in p.read_text(encoding="utf-8") for p in _skills) and "Bash(python3 *scripts/new_doc.py*)" in (W/"srcs"/"backend"/".claude"/"settings.json").read_text() and "Write(docs/**)" in (W/"srcs"/"backend"/".claude"/"settings.json").read_text())
# 토큰 먼저 (0.13.7): https 원격이면 토큰이 들어온 뒤에 받는다 · 토큰을 git 자격증명으로 저장
TW = W / "tokfirst"; shutil.rmtree(TW, ignore_errors=True); (TW/"s").mkdir(parents=True); (TW/"work").mkdir()
for f in ("init.py", "creds.py"): shutil.copy(KIT/f, TW/"s"/f)
_cfg = _j.loads((KIT/"repos.json").read_text()); _cfg["base"] = "https://bitbucket.org/example-ws/"; (TW/"s"/"repos.json").write_text(_j.dumps(_cfg))
_env = {k: v for k, v in os.environ.items() if k not in ("BITBUCKET_API_TOKEN", "JIRA_TOKEN", "JIRA_EMAIL")}
_r = subprocess.run([sys.executable, str(TW/"s"/"init.py"), "기획자", "--no-plugins", "--name", "충현"], cwd=TW/"work", capture_output=True, text=True, env=_env)
check("init(https 원격, 토큰 없음): 토큰 파일을 만들고 열어 두고, 저장소는 받지 않고 멈춘다", _r.returncode == 0 and (TW/"work/tokens.txt").exists() and "토큰이 들어온 뒤에" in _r.stdout and not (TW/"work/product").exists(), _r.stdout[-400:] + _r.stderr[-200:])
(TW/"work/tokens.txt").write_text((TW/"work/tokens.txt").read_text().replace("BITBUCKET_API_TOKEN=\n", "BITBUCKET_API_TOKEN=tok-zzz\n"))
_r = subprocess.run([sys.executable, str(TW/"s"/"init.py"), "기획자", "--no-plugins", "--name", "충현"], cwd=TW/"work", capture_output=True, text=True, env=dict(_env, GIT_TERMINAL_PROMPT="0", HOME=str(TW)))
check("init(토큰 있음): git 열쇠를 저장한 뒤 받기를 시도한다 · 토큰 값은 출력하지 않는다", "git 열쇠" in _r.stdout and "tok-zzz" not in _r.stdout and ("clone" in _r.stdout or "실패" in _r.stdout), _r.stdout[-500:] + _r.stderr[-200:])
# init — 내 이름 폴더(memo/people/<이름>/)와 HARNESS_ME (0.13.1); 빈 원격 방어
IW = W / "initw"; shutil.rmtree(IW, ignore_errors=True); (IW/"remotes").mkdir(parents=True); (IW/"work").mkdir()
for _n in ("backend", "memo"):
    subprocess.run(["git", "init", "-q", "--bare", "-b", "main", str(IW/"remotes"/f"{_n}.git")], check=True)
    subprocess.run([sys.executable, str(HROOT)+"/sync.py", "new", _n, "--into", str(IW/f"seed-{_n}")], check=True, capture_output=True); _sd = IW/f"seed-{_n}"/_n
    subprocess.run(["git", "init", "-q", "-b", "main", str(_sd)], check=True); g("add", "-A", cwd=_sd); g("commit", "-qm", "ORD-1 init", cwd=_sd); g("remote", "add", "origin", str(IW/"remotes"/f"{_n}.git"), cwd=_sd); g("push", "-q", "-u", "origin", "main", cwd=_sd)
subprocess.run(["git", "init", "-q", "--bare", "-b", "main", str(IW/"remotes"/"product.git")], check=True)   # 비어 있는 원격
shutil.copy(KIT/"creds.py", IW/"creds.py"); _it = IW/"init_test.py"; _it.write_text((KIT/"init.py").read_text(encoding="utf-8").replace('BASE = (os.environ.get("HARNESS_BASE") or CFG["base"]).rstrip("/") + "/"', f'BASE = "{IW}/remotes/"'), encoding="utf-8"); shutil.copy(KIT/"repos.json", IW/"repos.json")
_r = subprocess.run([sys.executable, str(_it), "백엔드", "--no-plugins", "--name", "홍길동"], cwd=IW/"work", capture_output=True, text=True, env=dict(os.environ, HARNESS_ME="")); o = _r.stdout + _r.stderr
check("init: memo/people/<이름>/README.md 만들어 origin main에 올림 · HARNESS_ME를 각 저장소 settings.local.json에", "memo/people/홍길동/ 만들어 올렸다" in o and (IW/"work/memo/people/홍길동/README.md").exists() and "memo: 홍길동 폴더" in g("log", "--oneline", "main", "-1", cwd=IW/"remotes/memo.git").stdout and _j.loads((IW/"work/backend/.claude/settings.local.json").read_text())["env"]["HARNESS_ME"] == "홍길동", o[-500:])
check("init: 커밋 없는 원격(product)은 '비어있음'으로 알리고 빈 폴더를 남기지 않는다", "비어있음 product/" in o and not (IW/"work/product").exists(), o[-500:])
_r = subprocess.run([sys.executable, str(KIT/"memo.py"), "add", "init 뒤 첫 메모"], cwd=IW/"work/backend", capture_output=True, text=True, env=dict(os.environ, HARNESS_ME="홍길동")); o = _r.stdout + _r.stderr
check("memo.py add (옆 저장소에서, --repo 없이): ../memo 를 찾아 적고 올린다", _r.returncode == 0 and "올렸다" in o and "init 뒤 첫 메모" in g("log", "--oneline", "main", "-1", cwd=IW/"remotes/memo.git").stdout, o[-300:])
_r = subprocess.run([sys.executable, str(_it), "백엔드", "--no-plugins", "--name", "홍길동"], cwd=IW/"work", capture_output=True, text=True); check("init 두 번째: 메모 폴더 '있음', 다시 커밋하지 않음", "있음   memo/people/홍길동/" in _r.stdout, _r.stdout[-300:])
(O/"docs/questions").mkdir(exist_ok=True); (O/"docs/questions/Q-01.md").write_text(fm(id="Q-01", type="question", title="취소 기준?", status="NEEDS-DECISION", owner="기획자") + "asked_by: backend\n")
c, o = run(R3, "scripts/gen_index.py", "--team", str(PR), "--write"); team_md = (PR/"TEAM.md").read_text(); check("gen_index --team: 저장소 가로질러 결정 대기·최근 결정·변경", c == 0 and "## other" in team_md and "결정 대기 1" in team_md and "Q-01 취소 기준?" in team_md and "즉시는 5초로 한다" in team_md and "ORD-50" in team_md, team_md[:600])
check("킷 .gitignore에 세션 상태 파일", ".claude/harness-state.json" in (W/"srcs"/"backend"/".gitignore").read_text())
(R3/"docs/a.md").write_text("changed"); r = hk(); check("pull 훅: 추적 파일 변경 있으면 안 당기고 알림", "커밋되지 않은 변경" in r.stdout, r.stdout[-200:]); (R3/"docs/a.md").write_text("a")
(R3/"docs/untracked.md").write_text("u"); r = hk(); check("pull 훅: 미추적 파일(생성물)은 막지 않는다", "커밋되지 않은 변경" not in r.stdout, r.stdout[-200:]); (R3/"docs/untracked.md").unlink()
g("checkout", "-q", "-b", "feature/ORD-9-y"); r = hk(); check("pull 훅: feature 브랜치면 알림", "main에서 새 브랜치" in r.stdout, r.stdout[-200:]); g("checkout", "-q", "main")
g("remote", "set-url", "origin", "/nonexistent.git"); r = hk(); check("pull 훅: 원격 불가면 알림하고 진행", "당기지 못했다" in r.stdout, r.stdout[-200:])

print("pr.py rebase · INDEX 비추적")
g("remote", "set-url", "origin", str(PR/"origin.git")); g("checkout", "-q", "main"); g("pull", "-q", "--ff-only")
g("checkout", "-q", "-b", "feature/ORD-30-rb"); (R3/"docs/mine.md").write_text("m"); g("add", "-A"); g("commit", "-qm", "ORD-30 mine")
(O/"docs/theirs.md").write_text("t"); g("add", "-A", cwd=O); g("commit", "-qm", "ORD-31 theirs", cwd=O); g("push", "-q", "origin", "main", cwd=O)
c, o = run(R3, "scripts/pr.py", "ORD-30 rebase test"); log = subprocess.run(["git", "log", "--oneline", "origin/feature/ORD-30-rb"], cwd=R3, capture_output=True, text=True).stdout
check("pr: push 전에 origin/main 위로 rebase (원격 브랜치에 theirs 포함)", c == 0 and "ORD-31 theirs" in log and "ORD-30 mine" in log, o[-300:] + log)
g("checkout", "-q", "main"); g("pull", "-q", "--ff-only"); g("checkout", "-q", "-b", "feature/ORD-32-cf"); (R3/"docs/same.md").write_text("A"); g("add", "-A"); g("commit", "-qm", "ORD-32 A")
(O/"docs/same.md").write_text("B"); g("add", "-A", cwd=O); g("commit", "-qm", "ORD-33 B", cwd=O); g("push", "-q", "origin", "main", cwd=O)
c, o = run(R3, "scripts/pr.py", "ORD-32 conflict"); st = subprocess.run(["git", "status", "--porcelain"], cwd=R3, capture_output=True, text=True).stdout
check("pr: 충돌이면 rebase --abort 후 파일명과 함께 멈춤, 트리 깨끗", c != 0 and "충돌" in o and "same.md" in o and st.strip() == "", o[-300:] + st)
K = W / "srcs" / "backend"; check("킷 .gitignore에 docs/INDEX.md·.harness/ (생성물)", "docs/INDEX.md" in (K/".gitignore").read_text() and ".harness/" in (K/".gitignore").read_text())
check("킷 Pipelines가 하네스를 clone해 검사 전에 목차를 만든다 (저장소에 스크립트 없음)", (K/"bitbucket-pipelines.yml").read_text().index("git clone") < (K/"bitbucket-pipelines.yml").read_text().index("gen_index.py") < (K/"bitbucket-pipelines.yml").read_text().index("docs_check.py") and not (K/"scripts").exists())
check("init이 clone 직후 목차를 만든다", (IT/"work/backend/docs/INDEX.md").exists())

print("pr.py approve 경로")
g("remote", "set-url", "origin", "https://bitbucket.org/your-workspace/backend.git")
c, o = run(R3, "scripts/pr.py", "inbox", "--dry-run"); check("pr inbox dry-run", c == 0 and "pullrequests?state=OPEN" in o, o[-200:])
c, o = run(R3, "scripts/pr.py", "show", "12", "--dry-run"); check("pr show dry-run (diffstat)", c == 0 and "/12/diffstat" in o, o[-200:])
c, o = run(R3, "scripts/pr.py", "merge", "12", "--comment", "승인: 기획자", "--dry-run"); check("pr merge dry-run: 코멘트→approve→merge", c == 0 and o.index("/comments") < o.index("/approve") < o.index("/merge"), o[-300:])
c, o = run(R3, "scripts/pr.py", "merge", "12", env={"BITBUCKET_TOKEN": "x"}); check("pr merge: 저장소 토큰으로는 거부, 웹 링크 안내", c != 0 and "사람의 자격증명" in o and "pull-requests/12" in o, o[-300:])
c, o = run(R3, "scripts/pr.py", "inbox", "--brief"); check("pr inbox --brief: 자격증명 없으면 조용", c == 0 and o.strip() == "", o[-200:])

print("pr --direct · remote --mode · gitleaks 단계")
g("remote", "set-url", "origin", str(PR/"origin.git")); g("checkout", "-q", "main"); g("pull", "-q", "--ff-only")
c, o = run(R3, "scripts/pr.py", "ORD-40 direct", "--direct", "--dry-run"); check("pr --direct dry-run (main)", c == 0 and '"direct": true' in o, o[-200:])
g("checkout", "-q", "-b", "feature/ORD-41-x"); c, o = run(R3, "scripts/pr.py", "ORD-41 x", "--direct", "--dry-run"); check("pr --direct는 main 아니면 멈춤", c != 0 and "main에서만" in o, o[-200:]); g("checkout", "-q", "main")
(O/"docs/d2.md").write_text("d2"); g("add", "-A", cwd=O); g("commit", "-qm", "ORD-42 remote", cwd=O); g("push", "-q", "origin", "main", cwd=O)
(R3/"docs/d1.md").write_text("d1"); g("add", "-A"); g("commit", "-qm", "ORD-43 local")
c, o = run(R3, "scripts/pr.py", "ORD-43 direct push", "--direct"); log = subprocess.run(["git", "log", "--oneline", "origin/main"], cwd=R3, capture_output=True, text=True).stdout
check("pr --direct: rebase 후 main push (양쪽 커밋)", c == 0 and "ORD-42 remote" in log and "ORD-43 local" in log, o[-300:] + log)
c, o = run(Path(HARNESS_SYNC).parent, "remote.py", "--dry-run", "setup", "product", "--mode", "direct", env={"BITBUCKET_TOKEN": "x"}); check("remote setup --mode direct: push 제한 없음, force·delete는 있음", c == 0 and '"kind": "push"' not in o and '"kind": "force"' in o, o[-300:])
check("Pipelines에 gitleaks 단계 + AGENTS.md 자리표시자 검사", "gitleaks" in (K/"bitbucket-pipelines.yml").read_text() and "KEY-[0-9]' AGENTS.md" in (K/"bitbucket-pipelines.yml").read_text())

print("sync update — 옛 CLAUDE.md 지도를 AGENTS.md로 이관")
OLD = W / "oldrepo"; shutil.rmtree(OLD, ignore_errors=True); subprocess.run([sys.executable, HARNESS_SYNC, "new", "ui", "--into", str(W/"olds")], check=True, capture_output=True); OLD = W/"olds"/"ui"
(OLD/"CLAUDE.md").write_text((OLD/"AGENTS.md").read_text(encoding="utf-8").replace("# ui", "# ui (옛 지도)"), encoding="utf-8"); (OLD/"AGENTS.md").unlink()
subprocess.run([sys.executable, HARNESS_SYNC, "update", str(OLD)], check=True, capture_output=True)
check("옛 CLAUDE.md 지도 → AGENTS.md로 이름 바꿈, 내용 보존, CLAUDE.md는 @AGENTS.md", (OLD/"AGENTS.md").exists() and "(옛 지도)" in (OLD/"AGENTS.md").read_text() and (OLD/"CLAUDE.md").read_text().strip() == "@AGENTS.md")
(OLD/".gitignore").write_text("snapshot/\n"); (OLD/".claude/skills/ask").mkdir(parents=True, exist_ok=True); (OLD/".claude/skills/ask/SKILL.md").write_text("old copy"); (OLD/"scripts").mkdir(exist_ok=True); (OLD/"scripts/docs_check.py").write_text("old"); (OLD/"scripts/gen_index.py").write_text("old")
subprocess.run([sys.executable, HARNESS_SYNC, "update", str(OLD)], check=True, capture_output=True); check("sync update가 .gitignore 필수 항목을 채우고 v0.11 복사본(스킬·스크립트)을 지운다", all(x in (OLD/".gitignore").read_text() for x in ("docs/INDEX.md", ".claude/harness-state.json", ".claude/settings.local.json", ".harness/")) and "snapshot/" in (OLD/".gitignore").read_text() and not (OLD/".claude/skills").exists() and not (OLD/"scripts").exists())
check("공통 규칙은 RULES.md → 세션 훅이 주입 (맥락·결정 기록·스킬 접두)", "[변경]" in (CORE/"RULES.md").read_text() and "결정-기록.md" in (CORE/"RULES.md").read_text() and "/core:ask" in (CORE/"RULES.md").read_text())
check("build --check: 역할 플러그인 사본 = 코어", subprocess.run([sys.executable, str(HROOT)+"/build.py", "--check"], capture_output=True).returncode == 0)
check("역할 플러그인 스킬은 자기 루트의 scripts를 부른다 (${CLAUDE_PLUGIN_ROOT})", '"${CLAUDE_PLUGIN_ROOT}/scripts/new_doc.py"' in (Path(str(HROOT)+"/plugins/product/skills/policy/SKILL.md")).read_text() and (Path(str(HROOT)+"/plugins/product/scripts/new_doc.py")).exists())
check("플러그인 매니페스트: 역할 → 코어 의존", _j.loads(Path(str(HROOT)+"/plugins/dev/.claude-plugin/plugin.json").read_text())["dependencies"] == ["core"] and _j.loads(Path(str(HROOT)+"/plugins/frontend/.claude-plugin/plugin.json").read_text())["dependencies"] == ["dev"])

print(f"\n{ok} passed · {fail} failed")
